// Code generated by goyacc parser.y. DO NOT EDIT.

//line parser.y:2
package main

import __yyfmt__ "fmt"

//line parser.y:2
import (
	"fmt"
)

//line parser.y:8
type yySymType struct {
	yys int
	s   string
}

const COMA = 57346
const SEMI = 57347
const NEW_LINE = 57348
const QUESTION = 57349
const BEGIN_EXP = 57350
const END_EXP = 57351
const DOT = 57352
const BEGIN_ARR = 57353
const END_ARR = 57354
const IDENT = 57355
const INTEGER = 57356
const OP_MUL = 57357
const OP_DIV = 57358
const OP_ADD = 57359
const OP_SUB = 57360
const OP_EQ = 57361
const OP_COMP = 57362
const UNARY_SUB = 57363

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"COMA",
	"SEMI",
	"NEW_LINE",
	"QUESTION",
	"BEGIN_EXP",
	"END_EXP",
	"DOT",
	"BEGIN_ARR",
	"END_ARR",
	"IDENT",
	"INTEGER",
	"OP_MUL",
	"OP_DIV",
	"OP_ADD",
	"OP_SUB",
	"OP_EQ",
	"OP_COMP",
	"UNARY_SUB",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:68

var ()

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 48,
	20, 0,
	-2, 24,
	-1, 49,
	19, 0,
	-2, 25,
}

const yyPrivate = 57344

const yyLast = 102

var yyAct = [...]int{

	20, 7, 19, 15, 31, 32, 12, 55, 31, 32,
	39, 14, 4, 35, 36, 37, 38, 34, 33, 12,
	28, 16, 17, 46, 18, 40, 41, 13, 9, 17,
	8, 44, 45, 47, 48, 49, 50, 51, 52, 53,
	42, 11, 54, 30, 12, 31, 32, 9, 58, 8,
	35, 36, 37, 38, 34, 33, 31, 32, 59, 2,
	30, 35, 36, 37, 38, 29, 33, 31, 32, 1,
	23, 24, 35, 36, 37, 38, 21, 22, 31, 32,
	9, 25, 8, 35, 36, 5, 6, 57, 27, 27,
	0, 9, 0, 8, 0, 56, 43, 26, 3, 0,
	0, 10,
}
var yyPact = [...]int{

	80, -1000, 80, -1000, 36, 21, -1000, -1000, 3, 17,
	-1000, 18, -1000, -1000, 63, 85, 69, 69, -1000, 56,
	35, 2, -1000, -1000, 63, 63, -1000, 69, 84, -1000,
	63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
	-2, -1000, 69, -1000, 35, -1000, 83, 35, 57, 46,
	-6, -6, 68, 68, 39, -1000, -1000, 63, -1000, 35,
}
var yyPgo = [...]int{

	0, 69, 59, 98, 12, 1, 2, 3, 0, 23,
}
var yyR1 = [...]int{

	0, 1, 2, 2, 3, 3, 3, 4, 4, 5,
	5, 5, 7, 7, 6, 6, 6, 8, 8, 8,
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
	8, 9, 9,
}
var yyR2 = [...]int{

	0, 1, 1, 2, 3, 2, 1, 1, 2, 4,
	3, 4, 1, 3, 0, 1, 3, 1, 1, 1,
	4, 3, 3, 4, 3, 3, 3, 3, 3, 3,
	2, 1, 3,
}
var yyChk = [...]int{

	-1000, -1, -2, -3, -4, 5, 6, -5, 13, 11,
	-3, 5, -5, 6, 8, -7, 4, -4, 6, -6,
	-8, 13, 14, 7, 8, 18, 12, 4, -7, 9,
	4, 10, 11, 20, 19, 15, 16, 17, 18, 8,
	-8, -8, -4, 12, -8, -8, -9, -8, -8, -8,
	-8, -8, -8, -8, -6, 9, 12, 4, 9, -8,
}
var yyDef = [...]int{

	0, -2, 1, 2, 0, 0, 6, 7, 0, 0,
	3, 0, 8, 5, 14, 0, 0, 12, 4, 0,
	15, 17, 18, 19, 0, 0, 10, 0, 0, 9,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 14,
	0, 30, 13, 11, 16, 21, 0, 31, -2, -2,
	26, 27, 28, 29, 0, 22, 23, 0, 20, 32,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:29
		{
			fmt.Println(yyDollar[1].s)
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:30
		{
			fmt.Println(yyDollar[2].s)
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:32
		{
			yyVAL.s = yyDollar[1].s + ";"
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:37
		{
			yyVAL.s = yyDollar[1].s + ";\n" + yyDollar[2].s
		}
	case 9:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:39
		{
			yyVAL.s = yyDollar[1].s + "(" + yyDollar[3].s + ")"
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:48
		{
			yyVAL.s = yyDollar[1].s + ", " + yyDollar[3].s
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:52
		{
			yyVAL.s = "nullptr"
		}
	}
	goto yystack /* stack new state and value */
}
